services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static/:/var/www/static/
      - ./media/:/var/www/media/
      - ./nginx/initiate/conf.d/:/etc/nginx/conf.d/
      - ./certbot/data:/var/www/certbot
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt/:rw
      - ./certbot/data:/var/www/certbot/:rw
    depends_on:
      - nginx
    command: >-
      certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}