# Generated by Django 4.1.2 on 2022-10-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifytoken",
            name="expires_at",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
