upstream backend {
    server welltest-backend:8080;
}

server {
    listen 443 ssl;
    server_name welltest-test.k4anubhav.com;

    client_max_body_size 100M;

    ssl_certificate /etc/letsencrypt/live/welltest-test.k4anubhav.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/welltest-test.k4anubhav.com/privkey.pem;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location /static/ {
        if ($http_origin = "https://welltest-test.k4anubhav.com") {
            add_header Access-Control-Allow-Origin "https://welltest-test.k4anubhav.com" always;
            add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Content-Type, Authorization";
        }

        alias /var/www/static/;
    }

    location /media/ {
        if ($http_origin = "https://welltest-test.k4anubhav.com") {
            add_header Access-Control-Allow-Origin "https://welltest-test.k4anubhav.com" always;
            add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Content-Type, Authorization";
        }

        alias /var/www/media/;
    }

    location / {
        proxy_pass http://backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}

server {
    listen 80;
    server_name welltest-test.k4anubhav.com;

    location ~/.well-known/acme-challenge {
        allow all;
        root /var/www/certbot;
    }

    return 301 https://$host:$request_uri;
}
